<a href="https://colab.research.google.com/github/202011988/DAP__/blob/main/Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import files
netflixCsv = files.upload()

Saving NetflixOriginals.csv to NetflixOriginals (1).csv

#오징어게임 유행
넷플릭스 오리지널 시리즈 인기도

In [21]:
df = pd.read_csv('NetflixOriginals.csv')
df

UnicodeDecodeError: ignored

#위드코로나
세계적 위드코로나 진행 상황

In [13]:
import pandas as pd
import io

df = pd.read_csv('Covid19InfState.csv')
df

       1  20200101  ...   2020-01-31 17:47:33.33  2020-02-03 12:21:56.56
0      2  20200202  ...   2020-02-03 12:22:49.49                     NaN
1      3  20200203  ...   2020-02-03 14:41:17.17  2020-02-04 14:19:46.46
2      4  20200204  ...   2020-02-03 21:26:59.59                     NaN
3      5  20200205  ...   2020-02-04 23:56:31.31   2020-02-05 9:43:16.16
4      6  20200205  ...   2020-02-05 20:05:40.40  2020-02-06 10:05:36.36
..   ...       ...  ...                      ...                     ...
685  708  20211125  ...  2021-11-25 09:00:47.897                     NaN
686  709  20211126  ...  2021-11-26 09:03:03.973                     NaN
687  710  20211127  ...  2021-11-27 09:32:36.026                     NaN
688  711  20211128  ...  2021-11-28 08:58:53.394                     NaN
689  712  20211129  ...  2021-11-29 09:05:16.736                     NaN

[690 rows x 14 columns]

In [16]:
df = pd.read_csv("day_wise.csv")
df

           Date  Confirmed  ...  Deaths / 100 Recovered  No. of countries
0    2020-01-22        555  ...                   60.71                 6
1    2020-01-23        654  ...                   60.00                 8
2    2020-01-24        941  ...                   72.22                 9
3    2020-01-25       1434  ...                  107.69                11
4    2020-01-26       2118  ...                  107.69                13
..          ...        ...  ...                     ...               ...
183  2020-07-23   15510481  ...                    7.27               187
184  2020-07-24   15791645  ...                    7.16               187
185  2020-07-25   16047190  ...                    7.04               187
186  2020-07-26   16251796  ...                    6.98               187
187  2020-07-27   16480485  ...                    6.91               187

[188 rows x 12 columns]

In [20]:
from dateutil.parser import parser
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

plt.rcParams.update({'figure.figsize' : (10, 7),
                     'figure.dpi' : 120})

df = df.dropna(axis=1)
df = pd.read_csv("day_wise.csv", parse_dates=['date'], index_col='date')

plt.figure(figsize=(16,5), dpi = 100)
plt.plot(df.index, df.value, color = 'tab:red')
plt.gca().set(title="temp", xlabel = "x", ylabel = "y")
plt.show()

ValueError: ignored